### ISSUE TITLE
[Request] Update to Minecraft 1.12

### ISSUE THREAD

**Issue by NekoAmps** [MinimumContent/muon#7]
The current version made for MC1.11 isn't compatible with 1.12, sadly. So I'd really like an update!

Here's a snip from a crashlog of me trying to use Muon in 1.12:

-- Head --
Thread: Server thread
Stacktrace:
	at gd.izno.mc.muon.MuonHeightMap.defaultHeights(MuonHeightMap.java:60)
	at gd.izno.mc.muon.MuonHooks.villageModTerrain(MuonHooks.java:351)
	at net.minecraft.world.gen.structure.MapGenVillage$Start.<init>(SourceFile:123)
	at net.minecraft.world.gen.structure.MapGenVillage.func_75049_b(SourceFile:87)

-- Feature being prepared --
Details:
	Is feature chunk: True
	Chunk location: 21,33
	Chunk pos hash: 141733920789
	Structure type: net.minecraft.world.gen.structure.MapGenVillage
Stacktrace:
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:40)
	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:34)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185932_a(ChunkGeneratorOverworld.java:228)

**Comment by TrinaryLogic** [comment]
Finally uploaded a 1.12 version to Curseforge, which should be available shortly. Sorry for the long delay on this! It seems every time I work on Muon I'm doing it on a different computer and I had problems with my dev environment. Lessons learned! :)
